"""Knowledge-base image semantic parsing with the existing Vision LLM."""
from __future__ import annotations

import base64
from pathlib import Path

from langchain_core.messages import HumanMessage

from agent.llm import get_vision_llm


_MIME_TYPES = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
}

_VISION_PROMPT = """你是企业知识库的图片语义索引器。请阅读图片并生成可被语义检索的结构化中文描述。

必须覆盖以下字段，没有的信息写“未检测到”，不要编造：
1. 图片类型
2. 图片主要内容
3. 图片中的文字
4. 表格/图表信息
5. 关键数据
6. 趋势或关系
7. 语义上下文

输出使用简洁 Markdown 字段列表。关键数据和结论必须来自图片。"""


def image_data_url(path: str | Path) -> str:
    image_path = Path(path)
    mime_type = _MIME_TYPES.get(image_path.suffix.lower(), "image/png")
    encoded = base64.b64encode(image_path.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


async def describe_image(
    image_path: str | Path,
    *,
    filename: str,
    page_number: int | None = None,
    slide_number: int | None = None,
    section_title: str | None = None,
    ocr_text: str = "",
) -> str:
    """Return a text semantic representation generated by the configured Vision LLM."""
    context = [f"文件名：{filename}"]
    if page_number:
        context.append(f"来源页码：{page_number}")
    if slide_number:
        context.append(f"来源幻灯片：{slide_number}")
    if section_title:
        context.append(f"来源标题：{section_title}")
    if ocr_text:
        context.append("OCR 参考文本：\n" + ocr_text[:3000])
    context_text = "\n".join(context)

    llm = get_vision_llm(streaming=False)
    message = HumanMessage(
        content=[
            {"type": "text", "text": f"{_VISION_PROMPT}\n\n{context_text}"},
            {"type": "image_url", "image_url": {"url": image_data_url(image_path)}},
        ]
    )
    response = await llm.ainvoke([message])
    description = response.content
    if isinstance(description, list):
        description = "\n".join(
            item.get("text", "") for item in description
            if isinstance(item, dict) and isinstance(item.get("text"), str)
        )
    description = description.strip()
    if not description:
        raise RuntimeError("Vision parse failed: empty response")
    return f"【图片语义描述】\n{description}\n\n原始文件：{filename}"
